name: gxWarps
main: com.gxbriiel.gxwarps.Warps
author: gxbriiel
version: 1.0.0
commands:
  setwarp:
  warps:
  editwarps:
permissions:
  gxwarps.acess:
    description: Acess to the /warps command.
    default: op
  gxwarps.setwarp:
    description: Permission to create a warp.
    default: op
  gxwarps.editwarp:
    description: Permission to edit warps.
    default: op